### ISSUE TITLE
No documents match your search terms

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/Covid-19_WHO#4]
@viniciusandrade and @botturam could you help explaining why the interface is not retrieving documents? I am doing something wrong?
![Captura de tela de 2021-11-08 11-58-19](https://user-images.githubusercontent.com/2152778/140764969-e980bbc7-c3a2-4ada-8e7d-ee9a32b3b5e2.png)
![Captura de tela de 2021-11-08 11-58-13](https://user-images.githubusercontent.com/2152778/140764973-f12c6aa3-b2f9-4e54-a9a3-0820aa67de53.png)

**Comment by viniciusandrade** [comment]
@heitorbarbieri  neste exemplo precisa informar que o correto é sempre utilizar as aspas duplas para a busca por termos compostos.

**Comment by heitorbarbieri** [comment]
@viniciusandrade apenas para comentário, vendo os resultados abaixo:

title,abstract,subject

SEARCH           RESULTS 
post             8.163
"post"           8.163
'post'           1
covid            127.359
"covid"          127.359
'covid'          15
"post covid"     267
'post covid'     0
post covid       4.429
post AND covid   4.429
post OR covid    131.093


title

SEARCH           RESULTS
post             5.753
"post"           5.753
'post'           5.753
covid            249.808
"covid"          249.808
'covid'          249.808
"post covid"     2.928
'post covid'     4.390
post covid       4.390
post AND covid   4.390
post OR covid    251.171

pude reparar que as aspas simples em title,abstract,subject se comportam como um caracter normal, o que significa que precisam estar no texto enquanto que em title elas são simplesmente ignoradas, isto é, o resultado da busca é igual à expressão sem as mesmas.

**Comment by heitorbarbieri** [comment]
Because the differences in behaviour between using only title and using title, abstract and subject the seach using ' sign should be replalced by " sign when we want to search an expression as it is, i. e., using all words and following their positions.
